[package]
name = 'nft'
version = '1.0.0'

[dependencies]
MoveStdlib = { local = "../../../aptos-core/aptos-move/framework/move-stdlib" }
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework"}
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token"}

[addresses]
wav3 = "0x0bf137ced519f68a3ac97eee8007712eeb7c5c982ebf9c79aed9666627a44aaa"